### PR TITLE
Clarifying the db injection hack example

### PR DESCRIPTION
**Pull request by timtomch**
The text following the SQL injection hack example was referring to a "project name" whereas the example is about an user ID. I think this should be corrected.

### CODE REVIEW

**Comment by acabunoc** [comment]
Hey @timtomch! Good to hear from you :)

Could you make all your edits in the markdown file (10-prog.md)? Usually we regenerate the html after we merge in the markdown changes.

Thanks!

**Comment by timtomch** [comment]
Mmh, I did the change to the markdown file, then ran make preview and it regenerated the html as well. Both are included in the pull request. Are you saying the PR should contain only the .md file?

FYI, I also completed a version of the SQL lesson with the "library" example we had prototyped last year. Used it last week with a crowd of librarians and they seemed to like it: https://github.com/timtomch/sql-novice-library

**Comment by acabunoc** [comment]
Yes, we normally ask that only markdown files are committed. From [CONTRIBUTING.md](https://github.com/swcarpentry/sql-novice-survey/blob/gh-pages/CONTRIBUTING.md#getting-started):

>When editing lessons, please only commit changes to the Markdown files, not the generated HTML. We will re-create the HTML after your pull request is merged. (Working this way ensures that each change only needs to be reviewed once, in one place.)

It really helps make my job easier! Thanks for your help here :)

Also, it looks like you've added a few more substantial changes to this PR. We're currently discussing moving the getting started info in a couple others PRs: #87 & #112 if you want to add your thoughts.

And THANK YOU for the link to the library prototype! We should find a place to add this to the lessons :) Maybe an 'other lessons' list?

**Comment by timtomch** [comment]
Thanks for the comments, also I wasn't aware that the later edits would be pushed to the same pull request... I'm still obviously not at ease with the whole collaborative editing setup :( sorry.

Closing this for now, I'll reopen one with just the md for the fix.

**Comment by acabunoc** [comment]
Hahah, yes GitHub is tricky! Usually 1 branch == 1 PR. 

Thanks again!

**Comment by timtomch** [comment]
Yeah, I should do this more often :)

BTW, what is the best workflow when you have run make preview (and updated the HTML files) but then want to submit a PR? I had to manually `git reset` the changed HTML files to previous commits before re-commiting and doing the PR. Is there a better way?

**Comment by acabunoc** [comment]
I individually `git add` each markdown file I've changed. Personally, I avoid `git add .` since that's led to some unintended commits from me in the past :) 

Once I've made the commit, I `git stash` to get rid of the unwanted changes but still have any in my stash *just in case*.

**Comment by timtomch** [comment]
This make so much sense. I feel foolish now. Thanks for your help and patience! :)

**Pull request closed without merging**
