### PR TITLE
Added section on entering and exiting SQL + on semicolon syntax

### PR DESCRIPTION
**Pull request by lwjohnst86**
As per request from @gvwilson after the online teaching practice, I added a section in the SQL select page on entering and exiting SQLite (novices, myself included, often don't know how to get out or in) as well as a section on forgetting to include the semicolon (again something that novices + myself have encountered and it gets confusing to figure out how to get out of it).

### CODE REVIEW

**Comment by timtomch** [comment]
Not to be nitpicky, but isn't the ; syntax SQLite's and not really SQL?

**Comment by lwjohnst86** [comment]
@timtomch Nope, though it depends.

http://en.wikipedia.org/wiki/SQL#Language_elements
http://www.w3schools.com/sql/sql_syntax.asp

**Comment by timtomch** [comment]
Huh, my bad then. Thanks for pointing it out! :)

**Comment by acabunoc** [comment]
Thanks @lwjohnst86!

I like the ; text! We definitely need that.

We moved the setup instructions for sqlite3 (including entering & exiting) to [discussion.md](https://github.com/swcarpentry/sql-novice-survey/blob/gh-pages/discussion.md). Move was done here: https://github.com/swcarpentry/sql-novice-survey/commit/71f5f37acc5cb6ab929fb7d4a8f11654aab3da6d

@mckays630 -- what do you think about the setup location? It looks like @lwjohnst86 & @gvwilson missed it in discussion.md.

**Comment by lwjohnst86** [comment]
As a first time viewer of the site, I went through the links sequentially. I had thought it strange that getting into and out of sqlite3 was not included. I actually never looked at the discussion.md file as I thought it was for something else, not for setup. Any reason why 00-setup.md was moved into discussion.md? It makes more sense (as someone who only recently looked around the sql site) that the setup is *before* the 01-select.md, not in the "Other resources" area. As a newcomer, I thought "Other resources" were for misc stuff, not for something important like entering and exiting. Just my 2 cents.

**Comment by acabunoc** [comment]
Hey @lwjohnst86 -- I'm not *entirely* sure why 00-setup.md was moved into discussion.md.

I just remember Greg mentioning that change should be made for the 5.3 release -- I assumed it had been agreed upon somewhere.  @mckays630 might know more, since he actually made the change.

email before the release:
screen shot 2015-05-28 at 12 30 10

Sorry I don't know more about that.

**Pull request merged**
