### PR TITLE
Change Visited.id to integer

### PR DESCRIPTION
**Pull request by kyrretl**
Since the Visited id column only contains integers we changed the column data type to integer in the Survey.db file.
We also updated episode 09 to correspond with the changes in Survey.db.

The figures used in episode 07 (join) were correct, ie. they already showed visited id to have integer data type

### CODE REVIEW

**Comment by remram44** [comment]
`text` is what is actually in the file ([`files/survey.db`](files/survey.db)), so that would need to be updated by a maintainer as well.

**Comment by kyrretl** [comment]
We updated it :-)

Kyrre

-----Original Message-----

**Comment by remram44** [comment]
I merged the changes in, thank you for your contribution!

I did not merge 66c84d27, it seems unrelated. Feel free to open new pull requests for further changes :wink:

**Comment by kyrretl** [comment]
Sure, will do a new PR. It was just a mistake that the last commit ended up here.

**Pull request closed without merging**
