### PR TITLE
Add solution to 'Selecting Major Site Identifiers'

### LINKED ISSUE #220: Missing solution to challenge: `Selecting Major Site Identifiers`
I'm not clear what this challenge is asking. Is it something like this?
`SELECT DISTINCT  substr(site,1,instr(site,'-')-1) as MajorSite from Visited;`

If so I can edit the wording and submit a PR.

### PR DESCRIPTION
**Pull request by gcapes**
Also clarify wording of question.

Fix #220.
See also #158.

### CODE REVIEW

**Comment by henrykironde** [comment]
Thanks @gcapes, Could we keep all reserved words as capital. substr and instr

**Comment by gcapes** [comment]
Both `substr` and `instr` are introduced in the text using lowercase, and they won't auto-capitalise using the tab key in the way that `SELECT` and `FROM` do. 
What's the rationale for wanting them capitalised?

**Comment by henrykironde** [comment]
Good question @gcapes. We try to make reserved words capitalized and also `AS`. I guess they missed that. It's not required. but it makes it easy to read code and more organized. I am open to any style that you prefer.

**Comment by jttkim** [comment]
@gcapes as a guess -- this might be because `SELECT` and `AS` are standard SQL keywords while `instr` etc. are implementation specific extensions?

**Comment by henrykironde** [comment]
ref example :https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions162.htm

**Comment by gcapes** [comment]
Ok, I've capitalised `AS` but left the rest so it's consistent with the rest of the lesson. Given it's such a minor change I've just amended my commit.
If you prefer to capitalise the other functions too, please go for it!

**Comment by henrykironde** [comment]
Thanks @gcapes, happy to see many things getting solved

**Pull request merged**
