### PR TITLE
Add solution: group_concat ordered. #158 Solutions

### PR DESCRIPTION
**Pull request by slimlime**
Worked on this in the recent workshop and initially used a nested query to achieve the desired result.

_ Solutions to SQL challenges #158
06 Aggregation Challenge: "Can you find a way to order the list by surname?"
Reduces a nested, ordered result set of concatenated `firstName`+`lastName` into a single tuple.

Uses a nested subquery to produce a concatenated `firstName`+`lastName` result set (ordered by the family name) before further concatenating each of those full name elements into a single output.

First contribution! Perhaps overly verbose in some places :). Can edit it down to just the plain SQL query.

### CODE REVIEW

**Comment by remram44** [comment]
Thank you for the contribution!

There is actually no need for a subquery, so I'm marking this as needing changes.

<details><summary>You can simply do (don't expand if you want to have another go at it, very similar to what you wrote but without subquery):</summary>

```
SELECT group_concat(personal || ' ' || family, ', ') FROM Person;
```
</details>

**Comment by remram44** [comment]
@r4space Why did you merge this? It is not correct

**Comment by r4space** [comment]
@remram44 Arg, sorry, I thought yours had effected the change, my bad.  Reverting now. 

@slimlime looking forward to your PR with the changes indicated by @remram44 (remove subquery use)

**Comment by slimlime** [comment]
Oops @remram44 did you have any suggested edits?

If I recall, months ago I found another function that made it elegant without subquery **but it wasn't supported in the environment provided at the time.**

**Comment by remram44** [comment]
Yes indeed I think your solution is correct, I had skipped over the ordering requirement. My fault. Sorry!

However it is much too complicated.

I'm starting to wonder what the intended solution to this challenge was. I'm thinking that removing the "ordered" requirement would make this more tractable, see #255

**Pull request merged**
