### PR TITLE
Completing ident -> id change

### PR DESCRIPTION
**Pull request by jangari**
Changes all remaining references to "ident" to "id", and "survey.db" to "survey.sqlite", including the sqlite file in the files directory.
Also changes typo in 06-agg. Reference to 'hours' is odd. Should be 'records'.
This pull request subsumes swcarpentry/sql-novice-survey#152

### CODE REVIEW

**Comment by jangari** [comment]
Pinging @acabunoc @gvwilson.

**Comment by acabunoc** [comment]
Thanks for this @jangari!

I'm really sorry but I can't find a record of discussion around renaming the database to survey.sqlite -- what was the reasoning behind this? Thanks!

**Comment by fmichonneau** [comment]
I had suggested the change in extension so the file could be displayed by the firefox sqlite plugin see #130

**Comment by jangari** [comment]
@acabunoc, I never recall seeing any (although I now see #130), but when I downloaded the data and ran through the material myself, I found it constantly referencing the wrong file. I could see various commits in the history changing some refs. 

I think I've caught the remaining references, but not 100% sure.

**Comment by acabunoc** [comment]
Thanks @fmichonneau & @jangari!

This seems like a good change -- especially with the sqlite plugin work.

I'll let @mckays630 weigh in and do the final review. I think I recently merged in a PR that changed everything to survey.db -- so you may need to look out for consistency @mckays630

**Comment by debpaul** [comment]
@acabunoc @fmichonneau @mckays630 @jangari If you've taught the SwC SQL Lesson recently, have you had install issues? See issues I've submitted (and other folks related tickets). If i do the SwC software installs as student, the command `sqlite3` at the bash prompt in Git Bash does not recognize the command to start `sqlite3`. Win 10, 64 bit. NOTE: IF I then go to the SQL instructor notes - and clone the git repository referred to there - then when I start `sqlite3` at the Git Bash prompt, it starts.

See https://github.com/swcarpentry/sql-novice-survey/issues/144
https://github.com/swcarpentry/sql-novice-survey/issues/118
https://github.com/swcarpentry/sql-novice-survey/issues/131

**Comment by jangari** [comment]
Hi @debpaul, I haven't taught it yet for a SC workshop, but I ran through the material at length and also ran a train-the-trainer for my colleagues, as we'll be adding the course to our training offering.

We run a slightly different setup with virtual machines with all the software and data preinstalled, so I made sure the SQL course has everything in the right location.

I suspect the reason that using survey.db works for you and not survey.sqlite, is that the file has not yet been renamed to survey.sqlite. A commit (#156) in this pull request fixes that.

I think the other issues you refer to are down to the same inconsistency. I taught my colleagues using VM images that include the survey.sqlite file, and from my own repository from which I'm making this pull request. So I'm confident that - while it may not fix all issues to do with installation - it'll at least be more consistent across systems.

**Comment by jangari** [comment]
I should add that I'll be teaching this course at a SC at Deakin in December (http://intersectaustralia.github.io/2016-12-12-Deakin) and if this pull request is merged by then, I will thoroughly test beforehand. If there are remaining issues I will probably base the workshop on my fork.

**Comment by jangari** [comment]
Any updates on this? Can I provide any more info?

**Comment by acabunoc** [comment]
Can you update this to also reverse some of the changes that this PR added:
https://github.com/swcarpentry/sql-novice-survey/pull/146

This way, we can move to a consistent `survey.sqlite`

**Comment by remram44** [comment]
Renaming `.db` to `.sqlite` is no longer crucial; if we switch to DB Browser to SQLite (#199), both extensions are accepted. I have a slight preference for `.sqlite` or `.sqlite3` over `.db` (which to me means Berkeley DB format, or some unspecified DB), and this definitely needs to be consistent across the lesson (`guide.md` uses `.sqlite`).

**Comment by henrykironde** [comment]
Thanks @jangari for the wonderful changes and suggestions. We have the changes in and I will add a ref: #176 as I close this PR.

**Pull request closed without merging**
