### PR TITLE
update on 1 challenge and replaced a reading value to null

### PR DESCRIPTION
**Pull request by xuf12**

### CODE REVIEW

**Comment by wking** [comment]
On Sun, Apr 05, 2015 at 10:31:38AM -0700, Xu Fei wrote:
>   * changed one reading value to null

This calls for knock-on changes to at least data/survey.csv and
likely to some query results in the topics themselves.

**Comment by xuf12** [comment]
@wking thanks for the reminder. Yes I'm aware of the consequent changes but wasn't sure how to proceed. Would you recommend me to submit a PR on the survey.csv and the changes in every section of the lesson as well, or should I wait for the topic maintainers' suggestion?

**Comment by wking** [comment]
On Sun, Apr 05, 2015 at 12:03:15PM -0700, Xu Fei wrote:
> Yes I'm aware of the consequent changes but wasn't sure how to
> proceed. Would you recommend me to submit a PR on the survey.csv and
> the changes in every section of the lesson as well, or should I wait
> for the topic maintainers' suggestion?

I think you should wait [1] (it's a lot of work wasted if it turns out
that the maintainers prefer addressing the issue with a different
approach), but Greg thinks you should proceed [2] (at least, that's
how I read it).  I think the odds are good that the maintainers agree
with the null-insertion approach, but nothing's 100% ;).  It's your
call how you balance the risk of wasted time vs. the speed of starting
before the maintainers green-light the general approach.

[1]: https://github.com/swcarpentry/sql-novice-survey/issues/57#issuecomment-89724151
[2]: https://github.com/swcarpentry/sql-novice-survey/issues/57#issuecomment-89764391

**Comment by mckays630** [comment]
@xuf12, am I correct in understanding that the change to lat constraint to 42 will cause the incorrect query to return an incorrect result?  I don't see a problem with changing a reading to a null value to illustrate a point but please make sure your PR has all of the cascading changes from survey.csv onward.

**Comment by xuf12** [comment]
@mckays630 yes, that's correct. I will add all the changes to the files that I can possibly think of to the PR. It also changes the survey.db file on the template site, which I don't know how to update.

**Comment by xuf12** [comment]
Just added an image that contains all 4 tables (only part of the table Survey is in it, as it's much longer than the rest). Please let me know whether it is a good idea. Thanks to @mjcollin for his suggestions on color for accessibility.

**Comment by gvwilson** [comment]
Closing as stale - tables in lesson show tables.

**Pull request closed without merging**
