### PR TITLE
Change primary key from 'ident' to 'id'

### PR DESCRIPTION
**Pull request by wking**
I've never seen 'ident' in the wild, but [Django uses 'id' for this][1].

[1]: https://docs.djangoproject.com/en/1.8/topics/db/models/#automatic-primary-key-fields

### CODE REVIEW

**Comment by acabunoc** [comment]
I like this @wking (I also haven't seen ident in the real world). I'd feel more comfortable putting this off till after we freeze just in case.

Thanks for all your helpful PRs though!

**Comment by iglpdc** [comment]
I'm +1 for this too.

**Comment by gvwilson** [comment]
'id' is a reserved word in some database managers (used for 
auto-incremented numeric ID column for tables), so I wanted to avoid 
using it.

**Comment by acabunoc** [comment]
ah, thanks for the insight @gvwilson

I think that's a pretty good reason to not change

**Comment by wking** [comment]
On Thu, Jan 14, 2016 at 12:35:36PM -0800, Greg Wilson wrote:
> 'id' is a reserved word in some database managers (used for
> auto-incremented numeric ID column for tables)…

Which database managers?

**Comment by acabunoc** [comment]
hm http://www.petefreitag.com/tools/sql_reserved_words_checker/?word=id

**Comment by gvwilson** [comment]
OK, I'm mistaken - :+1: for the change.

**Pull request merged**
