### PR TITLE
Update style

### PR DESCRIPTION
**Pull request by rgaiacs**
**Need to fix conflicts**:

- [ ] _includes/episode_navbar.html

### CODE REVIEW

**Comment by henrykironde** [comment]
@rgaiacs could you give me some update on this PR.

**Comment by rgaiacs** [comment]
> could you give me some update on this PR.

You email me asking that you didn't received the PR.

**Comment by henrykironde** [comment]
@rgaiacs, do we need the commits, or I could squash them?

**Comment by rgaiacs** [comment]
> do we need the commits

Yes. Otherwise future merge will be harder.

> I could squash them?

**Please don't.**

**Pull request merged**
