### PR TITLE
Best practice: Use explicit column names with INSERT

### PR DESCRIPTION
**Pull request by danmichaelo**
A fixed column order should not be assumed, it's good practice to always use explicit column names. This is also mentioned earlier in the lesson.

### CODE REVIEW

**Comment by henrykironde** [comment]
@remram44, this looks good to me

**Comment by remram44** [comment]
Maybe we should update [`09-create.md`](../blob/gh-pages/_episodes/09-create.md) too?

**Comment by henrykironde** [comment]
That sounds good to me, @danmichaelo would you want to add a PR for those suggested changes in case you have time?

**Comment by henrykironde** [comment]
Thank you @danmichaelo for these add

**Pull request merged**
