### PR TITLE
Additional challenge, and consistent reference to survey.sqlite

### PR DESCRIPTION
**Pull request by jangari**
Here's an additional challenge, since it's foreshadowed in 04-calc, it's a good idea to update the table once we know how.

Also, and I can't tell where the name change was, but it looks like survey.db is being modified to survey.sqlite. I've fixed all other references to the filename, and fixed the filename in files/.

### CODE REVIEW

**Comment by jangari** [comment]
Anyone monitoring these repos for pull requests?

**Comment by gvwilson** [comment]
@acabunoc @mckays630 ping

**Comment by acabunoc** [comment]
Thanks for the ping! Sorry for the delay @jangari, I'll take a look at this later today

**Comment by jangari** [comment]
Pinging @acabunoc @gvwilson.

**Comment by acabunoc** [comment]
closing this since the same changes appear in #156

**Pull request closed without merging**
