### PR TITLE
Made all SQL statements UPPER CASE

### PR DESCRIPTION
**Pull request by timtomch**
There seem to be a consensus that SQL statements are more legible with keywords in upper case. This implements the requested change as per https://github.com/swcarpentry/sql-novice-survey/issues/37

I also corrected some display glitches (*s have to be escaped in markdown tables) and a typo.

### CODE REVIEW

**Comment by wking** [comment]
On Mon, Feb 23, 2015 at 03:24:47PM -0800, Thomas Guignard wrote:

> There seem to be a consensus that SQL statements are more legible
> with keywords in upper case.

On a quick skim the changes looked good to me.

>     M 01-select.html (10)

But it's easier to review if you don't rebuild the HTML in your
feature branch.  For more details, see swcarpentry/lesson-template#159
and the “When editing lesson pages, you need only commit changes to
the Markdown source files” note merged in
swcarpentry/lesson-template#170.

**Comment by timtomch** [comment]
Oh sorry :( Do I need to commit again?

**Comment by gvwilson** [comment]
Don't worry about it this time 'round - the most important thing is to get this change in before other stuff with conflicts piles up.

**Comment by wking** [comment]
On Mon, Feb 23, 2015 at 03:38:08PM -0800, Greg Wilson wrote:
> Don't worry about it this time 'round - the most important thing is
> to get this change in before other stuff with conflicts piles up.

+1.

**Comment by timtomch** [comment]
So can I merge? I still need to PR the drawings, forgot to update them the first time round.

**Comment by gvwilson** [comment]
Please PR the drawings, then merge - thanks!

**Pull request merged**
