### PR TITLE
Add R lesson

### PR DESCRIPTION
**Pull request by jstaf**
This pull request adds in a set of SQL lesson materials for R, allowing SQL to be more easily taught in R-centric workshops. 

This version of the lesson has been [taught previously](https://cac-staff.github.io/summer-school-2016/), and a preview of the added materials is here: https://jstaf.github.io/sql-novice-survey/11-prog-R/

### CODE REVIEW

**Comment by acabunoc** [comment]
Thanks for this @jstaf! I'll take a look this week :)

**Comment by jstaf** [comment]
Figured I would check in and see what the status of this was. Any issues, or can this be merged?

**Comment by gvwilson** [comment]
@acabunoc can you please merge this one, or toss it at someone else? thx.

**Comment by acabunoc** [comment]
Thanks for the nudge! This looks great :tada:

**Pull request merged**
