### PR TITLE
Shift focus from complex query construction to schema design

### PR DESCRIPTION
**Pull request by wking**
This is a start at clearing out stuff I don't think we need to cover.
After I finish culling the current topics, I'll add some new content
to go into more details about schema design.  For general discussion
on this topic (higher level than the details of this PR), see #14.

This PR is a work in progress.  I'm floating it early because it's a
big change, and I think we'll want to talk over exactly what needs to
stay and what can go.  Once I get through the whole lesson, and have
made any adjustments we decide are needed, I'll remove the
work-in-progress label to signal that I think it's ready to merge.
Until then, this PR is just for discussion.

### CODE REVIEW

**Comment by wking** [comment]
@tsibley, you [expressed interest in this general idea earlier][1].  Do you want to lend a hand here?  Or review and provide feedback?

[1]: http://lists.software-carpentry.org/pipermail/seattle_lists.software-carpentry.org/2015-February/000238.html

**Comment by gvwilson** [comment]
Have these changes been tried in front of an audience yet?

**Comment by wking** [comment]
On Sun, Mar 29, 2015 at 04:54:23PM -0700, Greg Wilson wrote:
> Have these changes been tried in front of an audience yet?

I'm trying to finish my rough draft in time to trial it here [1].  The
trimming is in response to the way I felt my last pass through this
material (for [2]) went over.

[1]: https://efran.github.io/2015-04-09-UW/
[2]: https://ljwilliams.github.io/2014-03-17-uw/

**Comment by gvwilson** [comment]
Thanks - hope it goes well.

**Comment by wking** [comment]
On Mon, Mar 30, 2015 at 05:17:38AM -0700, Greg Wilson wrote:
> Thanks - hope it goes well.

Me too ;).  Any advice?  Were you just curious?  Or were you thinking
“I think this is going to crash and burn…”?  If you see a potential
pitfall, at least I'd be walking into it with my eyes open ;).

**Comment by tsibley** [comment]
@wking I'll get eyeballs on this PR this week.  Thanks for the heads up.

**Comment by tsibley** [comment]
> **Change primary key from 'ident' to 'id' [3a1c8c3]**

> I've never seen 'ident' in the wild, but Django [1] use 'id' for this.

> [1]: https://docs.djangoproject.com/en/1.8/topics/db/models/#automatic-primary-key-fields

Yep, `id` is pretty common lots of places.  The most common variants I see are using `foo_id` as the PK for table `foo`, so that the natural column names of FKs and PKs match.

**Comment by tsibley** [comment]
@wking Overall this looks good!  It's less of a rework than I was expecting (fearing?).  I added some relatively minor notes (see above) about specific commits.  A couple questions:

1. Are you planning more changes before Friday, or is this about where the lesson will land?
2. What do you think about the last section (10-prog)?  Last time in the R section at UW we didn't get anywhere close to it, and it wouldn't have been appropriate to throw Python at that audience anyway.  I don't know what happened in the Python room.  It seems bolted on to the lesson in a way that doesn't make a whole lotta sense to me.

Otherwise, we should likely figure out how to split up this lesson teaching-wise, by Wednesday/Thursday afternoon at least.  I'm comfortable with any parts of it.  Do you have a preference?  Not sure if we should only switch instructors once or if toggling twice is OK.

**Comment by wking** [comment]
On Mon, Apr 06, 2015 at 09:39:53PM -0700, Thomas Sibley wrote:
> 1. Are you planning more changes before Friday, or is this about
> where the lesson will land?

I'd like to discuss one-to-one, one-to-many, and many-to-many
relationships, but I didn't have time to work that up before this
workshop, so I think I'll leave it mostly as it stands.  As you imply,
making this transition in several more incremental steps is probably a
good thing ;).

> 2. What do you think about the last section (10-prog)?  Last time in
> the R section at UW we didn't get anywhere close to it, and it
> wouldn't have been appropriate to throw Python at that audience
> anyway.  I don't know what happened in the Python room.  It seems
> bolted on to the lesson in a way that doesn't make a whole lotta
> sense to me.

I think the goal is to try and tie the SQL material back into the
scripting language so learners see that they can store data in SQL and
process it in R/Python.  But by this point in the workshop folks will
be pretty saturated, so I'm fine just waving hands about that point.

Also, SQLite integration is pretty easy to in Python because there's a
standard library package for working with SQLite.  For an R class, you
should be able to use something like RSQLite [1], but I just found
that by searching “R SQLite” so I'm not sure where it stands on
popularity, stability, or other project lifecycle issues.

> Otherwise, we should likely figure out how to split up this lesson
> teaching-wise, by Wednesday/Thursday afternoon at least.  I'm
> comfortable with any parts of it.  Do you have a preference?  Not
> sure if we should only switch instructors once or if toggling twice
> is OK.

I don't have a preference either, or have a feeling for how accurate
the time estimates are.  I'd *like* to have an exercise where folks
design (and maybe create) a database from scratch after covering the
schema design section.  I haven't had time to work that up though, and
I'm not sure if it would be better to do another weather-ish
monitoring table (since that's science, and likely familiar enough to
all learners), or to pick something more different from the survey
example (tracking students/grades/courses/instructors?
Patients/diseases/hospitals/doctors?).  I think that would be a good
“around the coffee break” project, since that gives folks more time to
mull it over and ask questions.  But I doubt we'll get that far in the
hour and a half we have between 1 and 2:30pm.  If the current time
estimates are right, we could shift the sorting/duplication topic to
the back of the pack and bump the coffee break to 2:45.  But it's
probably not worth leaving so little time after the coffee break
before the end of the day.

Is the post-break time still SQL, or is some of it “thanks for
coming!” and big-picture wrap-up, or if it's a mixture?  Anyhow, I'll
flip a coin and suggest that you open and handle topics until our
halfway time (whatever that is), and then I'll pick up where you leave
off and finish things up.  Once we figure out how much time we have,
we can do any final shuffling, find the break, and drop any extra
topics.

[1]: http://cran.r-project.org/web/packages/RSQLite/index.html

**Comment by gvwilson** [comment]
On 2015-04-07 3:14 PM, W. Trevor King wrote:
> I'd like to discuss one-to-one, one-to-many, and many-to-many
> relationships, but I didn't have time to work that up before this
> workshop, so I think I'll leave it mostly as it stands.

I don't think we can get to that in a standard half-day lesson with our 
usual audience - 'join' is really about as far as we can push them.

Thanks,
Greg

**Comment by wking** [comment]
On Tue, Apr 07, 2015 at 12:37:11PM -0700, Greg Wilson wrote:
> On 2015-04-07 3:14 PM, W. Trevor King wrote:
> > I'd like to discuss one-to-one, one-to-many, and many-to-many
> > relationships, but I didn't have time to work that up before this
> > workshop, so I think I'll leave it mostly as it stands.
> 
> I don't think we can get to that in a standard half-day lesson with
> our usual audience - 'join' is really about as far as we can push
> them.

With the reorganization here, joins are now topic four (before this PR
they were topic seven).  I also dropped the calc topic.  That gives us
a bit more time to handle post-join content.  And if we're stopping
around topic seven, after this PR that means we'll be dropping
aggregation instead of schema design/hygiene.

**Comment by gvwilson** [comment]
I accept that we can teach all of this; I just don't believe that 
newcomers to SQL can _learn_ all of it in one long gulp.

**Comment by wking** [comment]
On Tue, Apr 07, 2015 at 05:36:37PM -0700, Greg Wilson wrote:
> I accept that we can teach all of this; I just don't believe that
> newcomers to SQL can _learn_ all of it in one long gulp.

That's certainly possible, although I think one of the main benefits
of frequent excercises is that it makes the lesson self-pacing.  When
learners start getting confused, they'll take longer to complete the
exercises.  Anyhow, we'll see how things go at UW and report back with
our assessment.

**Comment by tsibley** [comment]
> Is the post-break time still SQL, or is some of it “thanks for
coming!” and big-picture wrap-up, or if it's a mixture?  Anyhow, I'll
flip a coin and suggest that you open and handle topics until our
halfway time (whatever that is), and then I'll pick up where you leave
off and finish things up.  Once we figure out how much time we have,
we can do any final shuffling, find the break, and drop any extra
topics.

Last workshop, the post-break time was entirely SQL.  At 16:00 we concluded the SQL lesson and did a quick wrap up discussion with the class.  I'm fine with opening and handling topics until the break.

Also,

* I just noticed that the Designing Schema section talks about `nulls` but they aren't defined and taught until the following section, Missing Data.
* Merging in the SWC repo will pick up a handful of typo corrections. :)

**Comment by wking** [comment]
On Tue, Apr 07, 2015 at 08:40:06PM -0700, Thomas Sibley wrote:
> Last workshop, the post-break time was entirely SQL.  At 16:00 we
> concluded the SQL lesson and did a quick wrap up discussion with the
> class.  I'm fine with opening and handling topics until the break.

Sounds good.

> * I just noticed that the Designing Schema section talks about
>   `nulls` but they aren't defined and taught until the following
>   section, Missing Data.

I'll see what I can do about avoiding NULLs in that topic.

> * Merging in the SWC repo will pick up a handful of typo
>   corrections. :)

And #58 has landed too, so the only UW-specific content is in this PR.
I've rebased this branch onto the current tip to pull all that in.

**Comment by wking** [comment]
To make this easier to review, I've split off the drive-by changes
into #61, #62, #63, #64, #65, #66, #67, #68, #69, and #70.  That makes
it easy to review and merge orthogonal changes independently, but it
does mean there will be some merge conflicts if you try to merge them
all in one fell swoop ;).  If you run into any conflicts, I'm happy to
rebase the later branches onto whichever branches landed earlier.
Just let me know.

I'll post here with thoughts on how this shuffled approach went at UW
once I have time, but I have to run now.

**Comment by gvwilson** [comment]
Closing as stale (#61-#70 are being dealt with separately).

**Pull request closed without merging**
